const demo = [
  {id:'demo-1',name:'Juniper & Row',address:'Austin, TX · Independent home & lifestyle boutique',website:'https://juniperrow.example',type:'Home decor boutique',rating:4.8,reviews:126,demo:true},
  {id:'demo-2',name:'Sunday House Mercantile',address:'Austin, TX · Furniture and curated home goods',website:'https://sundayhouse.example',type:'Furniture & home goods',rating:4.7,reviews:89,demo:true},
  {id:'demo-3',name:'Form & Field Interiors',address:'Austin, TX · Residential design studio',website:'https://formandfield.example',type:'Interior design studio',rating:4.9,reviews:54,demo:true}
];
let prospects = [...demo], config = {foursquare:false,snov:false,resend:false,demo:true}, sortHigh=false;
const $=s=>document.querySelector(s), escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const backendPort=new URLSearchParams(location.search).get('backend')||'3000';
const apiOverride=new URLSearchParams(location.search).get('api');
const staticPreview=location.protocol==='file:'||!['3000','3177'].includes(location.port);
const API_BASE=(apiOverride|| (staticPreview?`http://localhost:${backendPort}`:'')).replace(/\/+$/,'');
async function request(url,body){let r;try{r=await fetch(`${API_BASE}${url}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}catch{throw new Error(`Cannot reach HomeScout API at localhost:${backendPort}. Start the Node server, then reload. VS Code Live Server only serves the page.`)}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Search request failed');return data}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),6000)}
function domainOf(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return ''}}
function render(){const list=$('#prospects');list.innerHTML='';$('#result-count').textContent=`${prospects.length} ${prospects.length===1?'prospect':'prospects'}`;$('#empty-state').classList.toggle('hidden',prospects.length>0);const ordered=[...prospects].sort((a,b)=>sortHigh?(b.rating||0)-(a.rating||0):0);ordered.forEach((p,i)=>{const row=document.createElement('article');row.className='prospect';const address=p.address||'United States';const rating=p.rating?`★ ${Number(p.rating).toFixed(1)} <span class="dot">·</span> ${p.reviews||0} reviews`:'';row.innerHTML=`<div class="store-icon">${['⌂','◈','▧'][i%3]}</div><div class="prospect-main"><div class="prospect-title"><h3>${escapeHtml(p.name)}</h3>${p.demo?'<span class="demo-tag">Illustrative demo</span>':''}</div><div class="prospect-meta"><span>${escapeHtml(p.type||'Retail prospect')}</span><span class="dot">·</span><span>${escapeHtml(address)}</span>${rating?`<span class="dot">·</span><span>${rating}</span>`:''}</div></div><div class="prospect-actions">${p.website&&!p.demo?`<a class="web-link" href="${escapeHtml(p.website)}" target="_blank" rel="noopener">Website ↗</a>`:''}<button class="contact-btn" data-id="${escapeHtml(p.id)}">Find contact &amp; write ↗</button></div>`;row.querySelector('button').addEventListener('click',()=>openContact(p,row.querySelector('button')));list.appendChild(row)})}
async function openContact(p,button){if(p.demo){toast('Demo records are illustrative. Run a live search first.');return}let first='there';$('#email-company').textContent=p.name;$('#contact-source').innerHTML=p.website?`Official retailer site: <a href="${escapeHtml(p.website)}" target="_blank" rel="noopener">open to find its published business email</a>.`:p.phone?`Retailer phone: ${escapeHtml(p.phone)}.`:`No retailer website or phone was listed.`;$('#email-to').value='';$('#email-subject').value=`A thoughtful fit for ${p.name}`;$('#email-text').value=`Hi ${first},\n\nI’m [Your Name], the maker behind [Your Brand]. We create [brief description of your home decor collection], and I thought it could be a lovely fit for ${p.name}.\n\nWould you be open to taking a look at our collection? I’d be glad to share a short line sheet and wholesale details.\n\nWarmly,\n[Your Name]\n[Your Brand]\n[Website]\n[Business postal address]\n\nIf this isn’t relevant, reply and I won’t follow up.`;$('#email-form').dataset.company=p.name;const submit=$('#email-form').querySelector('.send-btn');submit.innerHTML=config.resend?'Send email <span>↗</span>':'Open in email app <span>↗</span>';if(config.snov){const domain=domainOf(p.website);if(domain){button.disabled=true;button.textContent='Finding contacts…';try{const d=await request('/api/contacts',{domain});if(d.pending&&!d.emails.length){toast("Snov.io is still processing. Click Find contact again in a few seconds.")}else if(d.emails.length){const match=d.emails.find(e=>e.verification==='valid')||d.emails[0];$('#email-to').value=match.email;$('#contact-source').textContent=`Snov.io found ${match.email} (${match.position|| (match.type==="general"?"general company inbox":match.verification)}).`;first=match.firstName||'there';$('#email-text').value=$('#email-text').value.replace('Hi there,',`Hi ${first},`);toast(d.pending?'Snov.io search is still processing; these are the results available so far.':`Found ${d.emails.length} email(s) for ${d.domain}.`)}else toast(`Snov.io found no email for ${d.domain}. Enter one from the retailer’s website.`)}catch(e){toast(`${e.message} You can still enter an address manually.`)}finally{button.disabled=false;button.innerHTML='Find contact &amp; write ↗'}}}else{toast('Add Snov.io API User ID and API Secret to enable email lookup. You can still draft manually.')}$('#email-modal').showModal()}
function showBanner(message='Buyer discovery needs FOURSQUARE_API_KEY. Snov.io contact lookup needs its API User ID and API Secret in the server .env file.'){const b=$('#api-banner');b.classList.remove('hidden');b.textContent=message}
async function init(){let connected=false;try{const response=await fetch(`${API_BASE}/api/config`,{cache:'no-store'});if(!response.ok)throw new Error('API server unavailable');config=await response.json();connected=true}catch{}$('#integration-note').textContent=connected?(config.foursquare?'Foursquare key configured · live search depends on API quota':'API server connected · add provider keys on the server'):'API server not connected';if(!connected){const isGithub=location.hostname.endsWith('.github.io');const message=isGithub?(apiOverride?'Could not reach the deployed API. Check the backend URL and set APP_ORIGIN to this exact GitHub Pages origin on the backend.':'GitHub Pages only hosts the website files. Deploy the Node API separately, then open this page with ?api=https://YOUR-API-HOST. Keep API keys on the backend.'):`Live data needs the Node API server. In VS Code, run “node server.js” and keep it running. For a different API server, open this page with ?api=https://YOUR-API-HOST.`;showBanner(message)}else if(!config.foursquare)showBanner();render()}
$('#search-form').addEventListener('submit',async e=>{e.preventDefault();const city=$('#city').value.trim(),category=$('#category').value,btn=e.currentTarget.querySelector('button');if(!config.foursquare){showBanner();$('#result-title').textContent='Demo preview';toast('Connect Foursquare to search real US retailers.');return}btn.disabled=true;btn.querySelector('span').textContent='Searching…';try{const data=await request('/api/search',{city,category});prospects=data.prospects;$('#result-title').textContent=`Buyers near ${city}`;$('#api-banner').classList.add('hidden');render();if(!prospects.length)toast('No matches this time. Try a nearby city or another buyer type.')}catch(err){const banner=document.getElementById('api-banner');banner.classList.remove('hidden');banner.textContent=err.message;toast(err.message)}finally{btn.disabled=false;btn.querySelector('span').textContent='Find buyers'}});
$('#sort-btn').addEventListener('click',()=>{sortHigh=!sortHigh;render()});$('#cancel-email').addEventListener('click',()=>$('#email-modal').close());$('#email-form').addEventListener('submit',async e=>{e.preventDefault();const to=$('#email-to').value.trim(),subject=$('#email-subject').value.trim(),text=$('#email-text').value.trim();if(!config.resend){location.href=`mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(text)}`;toast('Draft opened in your email app. It has not been sent yet; review it and press Send there.');$('#email-modal').close();return}const btn=e.currentTarget.querySelector('.send-btn');btn.disabled=true;btn.innerHTML='Sending…';try{const data=await request('/api/send',{to,subject,text});$('#email-modal').close();toast(`Email sent successfully to ${to}.`);console.info('Email provider accepted message',data.id||'');}catch(err){toast(`Email was not sent: ${err.message}`)}finally{btn.disabled=false;btn.innerHTML=config.resend?'Send email <span>↗</span>':'Open in email app <span>↗</span>'}});init();

